---
- name: Registering system with Red Hat Subscription Management
  hosts: "{{ my_server }}"
  gather_facts: no
  # This playbook requires username and password to be input at runtime
  # You can do this with a Survey in the AAP GUI
  # The username and password are the credentials for access.redhat.com
  vars:
    username: "{{ username }}"
    password: "{{ password }}"
    status: "{{ status }}"
    
  tasks:
  
    # Gather the start time to use in a later playbook
    - name: Record the subscription_time
      delegate_to: 127.0.0.1
      register: subscription_time_pre
      ansible.builtin.command:
        cmd: "date '+%H:%M:%S'"

    # Make the start time available to other playbooks
    - name: Capture the subscription_time
      ansible.builtin.set_stats:
        data:
          subscription_time: "{{ subscription_time_pre.stdout }}"
  
    - name: Register and subscribe the system 
      community.general.redhat_subscription:
        username: "{{ username }}"
        password: "{{ password }}"
        state: "{{ status }}"