---
- name: Registering system with Red Hat Subscription Management
  hosts: all
  become: yes
  gather_facts: yes
  # This playbook requires username and password to be input at runtime
  # You can do this with a Survey in the AAP GUI
  # The username and password are the credentials for access.redhat.com
  vars:
    username: "{{ username }}"
    password: "{{ password }}"
    
  tasks:
  
  - name: UN-Register and subscribe the system 
    community.general.redhat_subscription:
      username: "{{ username }}"
      password: "{{ password }}"
      state: absent